version: '3'

services: 

  app_node:
    build: 
      context: node
      dockerfile: Dockerfile.prod
    container_name: app_node
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - db

  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports: 
      - "8080:80"
    depends_on:
      - app_node

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports: 
      - "3306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./scripts/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
